version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'
        volumes:
            - ./projet_php:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
           # Pour lancer un dump automatiquement au montage du conteneur
            - db_data:/var/lib/mysql
            - ./datadump.sql:/docker-entrypoint-initdb.d/dump.sql



    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8081:80'
        environment:
            - PMA_ARBITRARY=1

volumes:
    db_data: